spring:
   # DB config
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.225:3306/scm_tms_std?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initial-size: 5
    max-idle: 10 #连接池中最大空闲连接数
    min-idle: 5 #连接池中最小空闲连接数
    max-wait: 10000 #从连接池获取连接的最大等待时间
  redis:
    database: 0
    host: 192.168.0.225
    port: 6379
    password: huodada
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0