spring:
   # DB config
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.128:3306/tms-demo3.0?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initial-size: 5
    max-idle: 10 #连接池中最大空闲连接数
    min-idle: 5 #连接池中最小空闲连接数
    max-wait: 10000 #从连接池获取连接的最大等待时间
