debug: true

data:
  userName: root
  password: 123456
  
spring:
  application:
    name: service-provider
  zipkin: 
    base-url: http://192.168.0.41:9411
  cloud: 
    stream: 
      default-binder: rocketmq
      rocketmq: 
        binder:
          name-server: 192.168.3.241:9876
      # 定义name为output的binding
      bindings:
        output1:
          destination: test-topic
          content-type: application/json
        # 定义name为input的binding
        input1:
          destination: test-topic
          content-type: application/json
          group: test-group
    
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.111:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: 192.168.3.144
    
#logging
logging:
  config: classpath:logback.xml