debug: true

spring:
  application:
    name: service-gateway
  zipkin: 
    base-url: http://192.168.0.41:9411
    
server:
  port: 9080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.111:8761/eureka/
  instance:
    hostname: 192.168.3.144

zuul:
  ignored-services: authorization
  routes:
    #标识你服务的名字，这里可以自己定义，一般方便和规范来讲还是跟自己服务的名字一样
    service-provider:
      #服务映射的路径，通过这路径就可以从外部访问你的服务了，目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
      #这里zuul是自动依赖hystrix，ribbon的，不是面向单机
      path: /service-provider/**
      #这里一定要是你Eureka注册中心的服务的名称，是所以这里配置serviceId因为跟eureka结合了，如果单独使用zuul,那么就必须写自己机器的IP了，
      #如url:http://localhost:8080/  这样的不好就是写死IP了，万一这IP挂了，这高可用性，服务注册那套东西就用不起来了
      serviceId: service-provider
    authorization: 
      path: /authorization/**      
      
## Dubbo Registry
dubbo: 
  application: 
    name: service-gateway
  registry: 
    address: zookeeper://192.168.0.43:2181
    file: /tmp/dubbo.cache

#logging
logging:
  config: classpath:logback.xml